//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISA.API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LISAEntities : DbContext
    {
        public LISAEntities()
            : base("name=LISAEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attribute> Attribute { get; set; }
        public virtual DbSet<AttributeProduct> AttributeProduct { get; set; }
        public virtual DbSet<Catalog> Catalog { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<LimitDateShop> LimitDateShop { get; set; }
        public virtual DbSet<Media> Media { get; set; }
        public virtual DbSet<Operation> Operation { get; set; }
        public virtual DbSet<Page> Page { get; set; }
        public virtual DbSet<PositionProduct> PositionProduct { get; set; }
        public virtual DbSet<PriceProduct> PriceProduct { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Shop> Shop { get; set; }
        public virtual DbSet<TypeMedia> TypeMedia { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
