//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISA.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PositionProduct
    {
        public int Id { get; set; }
        public int Coord_X { get; set; }
        public int Coord_Y { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public int Id_Page { get; set; }
        public int Id_Product { get; set; }
    
        public virtual Page Page { get; set; }
        public virtual Product Product { get; set; }
    }
}
