//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISA.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceProduct
    {
        public int Id { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PriceBeforeTicket { get; set; }
        public Nullable<decimal> PriceBeforeCrossed { get; set; }
        public Nullable<decimal> ReductionEuro { get; set; }
        public Nullable<decimal> ReductionPercent { get; set; }
        public Nullable<decimal> AdvantageEuro { get; set; }
        public Nullable<decimal> AdvantagePercent { get; set; }
        public Nullable<decimal> Ecotaxe { get; set; }
        public int Id_Catalog { get; set; }
        public int Id_Product { get; set; }
    
        public virtual Catalog Catalog { get; set; }
        public virtual Product Product { get; set; }
    }
}
